### ISSUE TITLE
Bug: Compose Does Not Handle Multiple Relationships to the Same Service

### ISSUE THREAD

**Issue by JasonTheDeveloper** [microsoft/abstrakt#45]
**Describe the bug**
If a service referenced in multiple relationships' `To` and/or `From`, `compose` will not pick up on them and instead take the first relationship it encounters. 

If you look [here](https://github.com/microsoft/abstrakt/blob/9bb84456c6a6f7c0848c123f839d508ea5b20c79/internal/composeservice/composeservice.go#L38), `Compose` loops over the services in the constellation but when it comes to the relationships, it only looks if the service is referenced and returns the first relationship instance it appears in.

**To Reproduce**
1. Edit `sample/constellation/http_constellation.yaml` to look like the following:

    ```yaml
    Name: "HTTP Microservice Sample"
    Id: "d6e4a5e9-696a-4626-ba7a-534d6ff450a5"
    Services:
    - Name: "Sender 1"
      Id: "9e1bcb3d-ff58-41d4-8779-f71e7b8800f8"
      Type: "WormholeSender"
      Properties:
        CHAIN_ARG: "1"
    - Name: "Sender 2"
      Id: "5d43a954-7214-4872-9d8f-758bb4238aee"
      Type: "WormholeSender"
      Properties:
        CHAIN_ARG: "2"
    - Name: "Receiver"
      Id: "aa382e25-8662-4d11-bca9-d9a230c22487"
      Type: "WormholeReceiver"
      Properties: {}
    Relationships:
    - Name: "Sender to Sender Link"
      Id: "211a55bd-5d92-446c-8be8-190f8f0e623e"
      Description: "Link between the first and second senders"
      From: "9e1bcb3d-ff58-41d4-8779-f71e7b8800f8"
      To: "5d43a954-7214-4872-9d8f-758bb4238aee"
      Properties: {}
    - Name: "Sender to Receiver Link"
      Id: "ff5444b5-35b7-4688-98ef-56c2587b314d"
      Description: "Link between the second sender and receiver"
      From: "5d43a954-7214-4872-9d8f-758bb4238aee"
      To: "aa382e25-8662-4d11-bca9-d9a230c22487"
      Properties: {}
    - Name: "Sender to Receiver Link"
      Id: "ff5444b5-35b7-4688-98ef-56c2587b314e"
      Description: "Link between the second sender and receiver"
      From: "9e1bcb3d-ff58-41d4-8779-f71e7b8800f8"
      To: "aa382e25-8662-4d11-bca9-d9a230c22487"
      Properties: {}
    ```
2. Put a breakpoint on this [line](https://github.com/microsoft/abstrakt/blob/9bb84456c6a6f7c0848c123f839d508ea5b20c79/internal/composeservice/composeservice.go#L38).
3. Put this in your `.vscode/launch.json`:

    ```json
    {
            "name": "Launch",
            "type": "go",
            "request": "launch",
            "mode": "auto",
            "program":"${workspaceFolder}/main.go",
            "env": {},
            "dlvLoadConfig": {
                "followPointers": true,
                "maxVariableRecurse": 1,
                "maxStringLen": 5000,
                "maxArrayValues": 64,
                "maxStructFields": -1
            },
            "args": ["compose", "-f", "./sample/constellation/http_constellation.yaml", "-m", "./sample/constellation/http_constellation_maps.yaml", "-o", "./output/http_sample", "-v"]
        }
    ```
4. Run abstrakt in debug mode and notice how relationship `ff5444b5-35b7-4688-98ef-56c2587b314e` is ignored.

**Expected behavior**
If a service if referenced in multiple relationships, then compose should be able to handle it. 

**Screenshots**
N/A.

**Additional context**
N/A.
